[build]
builder = "NIXPACKS"
buildCommand = "cd proxy-js && npm install"

[deploy]
startCommand = "cd proxy-js && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PROXY_PORT = "7860"
